repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: linter.sh
        language: script

      - id: clang-tidy
        name: clang-tidy
        entry: linter.sh clangtidy
        language: script
